#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	30
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10

bspc config single_monocle	false
bspc config gapless_monocle	true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
#colors

bspc config normal_border_color "#24273A"
bspc config active_border_color "#363A4F"
bspc config focused_border_color "#363A4F"
#bspc config presel_feedback_color

picom --experimental-backends --backend=glx -f --blur-method=gaussian --blur-size=20 --blur-deviation=15 &
nitrogen --restore &
eww daemon &
polybar -r mainbar&
$HOME/.config/conky/start.sh &
